### ISSUE TITLE
scantofile.sh

### ISSUE THREAD

**Issue by derphilipp** [fcauwe/brother-scan#1]
Hi fcauwe,

thanks for the amazing work you have done!
I would very much like to use your script, but unfortunately the script file ("scantofile.sh") is missing. Are you going to complete your project to a first working state?

Cheers,

Philipp

**Comment by fcauwe** [comment]
Hi Philipp,

Thanks for noticing it, I just uploaded the file. I hope this helps.

François

**Comment by derphilipp** [comment]
Thank you very much!
